
services:
  postgres:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: behaylu
      POSTGRES_PASSWORD: ngst
      POSTGRES_DB: food_recipe_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  hasura:
    image: hasura/graphql-engine:v2.18.0
    restart: always
    ports:
      - "8081:8080"
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://behaylu:ngst@postgres:5432/food_recipe_db
      HASURA_GRAPHQL_ENABLE_CONSOLE: true
      HASURA_GRAPHQL_ADMIN_SECRET: getye
      HASURA_GRAPHQL_JWT_SECRET: '{"type": "HS256", "key": "my_favorite_jwt_secret_key_is_getye"}'
    depends_on:
      - postgres
volumes:
  postgres_data:




# CREATE TABLE users (
#     id SERIAL PRIMARY KEY,
#     username VARCHAR(50) UNIQUE NOT NULL,
#     email VARCHAR(100) UNIQUE NOT NULL,
#     password_hash TEXT NOT NULL,
#     created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
# );

# CREATE TABLE recipes (
#     id SERIAL PRIMARY KEY,
#     user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
#     title VARCHAR(100) NOT NULL,
#     description TEXT,
#     prep_time INTEGER, -- in minutes
#     category VARCHAR(50),
#     created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
# );

